"""Generate LaTeX result macros from a results.json file.

This enforces the analysis-bundle invariant: the note never contains a hand-typed
physics number. ``analysis.py`` writes ``results/results.json``; this module turns it
into ``results/results.tex`` defining one ``\\newcommand`` per result; the note quotes
numbers only through those macros.

Usage:
    python -m fisicai.writeup results/results.json > results/results.tex

Keys map to macro names by CamelCasing: ``m_z_peak`` -> ``\\MZPeak``. Nested objects
flatten with their path: ``{"cls": {"observed": ...}}`` -> ``\\ClsObserved``. Values are
rendered exactly as stored — round numbers to the intended precision in ``analysis.py``
(or store them as strings), never here.
"""

import argparse
import json
import re
import sys
from typing import Any


def macro_name(key: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", key)
    name = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not name or not name[0].isalpha():
        raise ValueError(f"cannot form a LaTeX macro name from key {key!r}")
    # digits are not allowed in LaTeX macro names; spell them out
    digits = "Zero One Two Three Four Five Six Seven Eight Nine".split()
    return re.sub(r"\d", lambda m: digits[int(m.group())], name)


def format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)  # shortest exact representation — no silent rounding
    return str(value)


def _flatten(results: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    flat: dict[str, Any] = {}
    for key, value in results.items():
        path = f"{prefix}_{key}" if prefix else key
        if isinstance(value, dict):
            flat.update(_flatten(value, path))
        else:
            flat[path] = value
    return flat


def results_to_tex(results: dict[str, Any]) -> str:
    lines = ["% Auto-generated by `python -m fisicai.writeup` -- do not edit by hand."]
    for key, value in _flatten(results).items():
        lines.append(f"\\newcommand{{\\{macro_name(key)}}}{{{format_value(value)}}}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("results_json", help="Path to results.json")
    parser.add_argument("--out", default=None, help="Output .tex path (default: stdout)")
    args = parser.parse_args()

    with open(args.results_json) as f:
        tex = results_to_tex(json.load(f))
    if args.out:
        with open(args.out, "w") as f:
            f.write(tex)
    else:
        sys.stdout.write(tex)


if __name__ == "__main__":
    main()
